osx_image: xcode8
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xcodebuild clean build -project Tailor.xcodeproj -scheme Tailor-iOS -sdk iphonesimulator
- xcodebuild test -project Tailor.xcodeproj -scheme Tailor-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
- xcodebuild clean build -project Tailor.xcodeproj -scheme Tailor-Mac -sdk macosx
- xcodebuild test -project Tailor.xcodeproj -scheme Tailor-Mac -sdk macosx

notifications:
  email: false
